#server
server:  port: 80
  servlet:    context-path: /
  tomcat:    threads:      max: 1000
      min-spare: 10
#spring 
spring:  datasource:    url: jdbc:mysql:///dbsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:    proxy-target-class: true
  task:    execution:      pool:        core-size: 10 #核心线程数，当池中线程数没达到core-size时，每来一个请求都创建一个新的线程
        queue-capacity: 256 #队列容量，当核心线程都在忙，再来新的任务，会将任务放到队列
        max-size: 128 #当核心线程都在忙，队列也满了，再来新的任务，此时会创建新的线程，直到达到maxSize
        keep-alive: 60 #当任务高峰过后，有些线程会空闲下来，这空闲现线程达到一定的时间会被释放。
        allow-core-thread-timeout: false
      thread-name-prefix: db-service-task-  
#mybatis

mybatis:  mapper-locations:  - classpath:/mapper/*/*.xml

#log 
logging:  level:    com.cy: debug
        

#shiro
shiro:
  loginUrl: /doLoginUI
  rememberMeManager:  
         cookie: 
            name: rememberMe
            maxAge: 604800
    
   
    
    
    
    
    
    